name: blindness_detection
channels:
  - defaults
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.8
  - pip
  - pip:
    - kaggle 
    - numpy
    - pandas
    - sklearn
    - mlflow
    - pillow
    - argparse
    - torch==1.8.1
    - torchvision==0.9.1
    - mlflow>=1.0